env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
rules:
  indent: ['error', 2, { SwitchCase: 1 }]
  linebreak-style: ['warn', 'windows']
  quotes: ['error', 'single']
  semi: ['error', 'never']
  # 别警告 any 了我就是要写你咋地吧
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
